USE phoneadvice;

INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (51,84,77);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (14,40,18);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (54,38,35);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (28,48,2);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (62,99,15);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (20,50,37);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (34,91,29);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (5,82,48);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (62,81,87);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (5,5,90);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (41,64,35);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (34,49,22);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (77,61,24);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (3,99,50);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (11,74,21);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (7,76,68);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (7,5,11);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (100,44,18);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (11,100,79);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (82,38,32);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (52,78,85);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (85,44,71);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (36,3,22);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (68,73,75);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (35,19,85);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (97,35,100);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (52,67,89);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (23,29,68);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (26,81,85);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (45,34,25);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (87,8,37);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (84,94,11);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (65,43,85);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (19,14,16);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (78,23,66);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (19,27,1);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (78,88,4);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (9,97,83);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (19,47,44);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (92,12,51);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (67,7,77);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (20,57,39);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (7,55,25);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (96,25,78);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (1,63,99);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (33,26,11);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (15,69,25);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (69,45,85);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (37,20,67);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (31,98,71);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (52,66,93);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (80,80,19);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (99,22,81);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (90,82,7);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (71,42,74);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (29,98,5);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (83,97,67);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (79,36,59);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (77,7,14);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (81,99,16);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (29,51,26);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (85,9,92);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (32,6,52);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (16,6,64);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (89,85,10);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (50,14,35);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (59,92,47);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (68,13,37);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (96,41,99);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (36,21,98);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (55,16,31);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (52,30,88);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (79,57,21);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (65,73,94);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (6,13,20);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (59,58,84);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (34,61,47);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (61,91,21);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (24,97,87);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (11,34,82);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (63,22,22);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (13,7,86);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (78,76,59);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (89,75,80);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (17,12,18);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (34,97,91);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (41,100,42);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (86,60,73);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (6,8,26);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (4,62,87);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (81,15,5);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (49,77,25);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (22,58,75);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (37,36,31);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (88,92,61);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (20,33,62);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (1,90,8);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (32,64,9);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (24,53,31);
INSERT INTO `phoneadvice`.`statistic` (`negative_density`, `neutral_density`, `positive_density`) VALUES (10,98,36);

INSERT INTO `phoneadvice`.`brand` (`assessment`, `description`, `name`) VALUES ('0', 'asd', 'Lg');
INSERT INTO `phoneadvice`.`brand` (`assessment`, `description`, `name`) VALUES ('0', 'asd', 'Samsung');
INSERT INTO `phoneadvice`.`brand` (`assessment`, `description`, `name`) VALUES ('0', 'asd', 'Xiaomi');
INSERT INTO `phoneadvice`.`brand` (`assessment`, `description`, `name`) VALUES ('0', 'asd', 'Motorola');
INSERT INTO `phoneadvice`.`brand` (`assessment`, `description`, `name`) VALUES ('0', 'asd', 'Huawei');
INSERT INTO `phoneadvice`.`brand` (`assessment`, `description`, `name`) VALUES ('0', 'asd', 'Asus');
INSERT INTO `phoneadvice`.`brand` (`assessment`, `description`, `name`) VALUES ('0', 'asd', 'Apple');
INSERT INTO `phoneadvice`.`brand` (`assessment`, `description`, `name`) VALUES ('0', 'asd', 'Nokia');

INSERT INTO `phoneadvice`.`gamma` (`max_price`, `min_price`, `name`) VALUES ('0', '150000', 'Baja');
INSERT INTO `phoneadvice`.`gamma` (`max_price`, `min_price`, `name`) VALUES ('350000', '150001', 'Media');
INSERT INTO `phoneadvice`.`gamma` (`max_price`, `min_price`, `name`) VALUES ('2000000', '350001
', 'Alta');

INSERT INTO `phoneadvice`.`specification` (`name`) VALUES ('Batería');
INSERT INTO `phoneadvice`.`specification` (`name`) VALUES ('Pantalla');
INSERT INTO `phoneadvice`.`specification` (`name`) VALUES ('Cámara');
INSERT INTO `phoneadvice`.`specification` (`name`) VALUES ('Almacenamiento');
INSERT INTO `phoneadvice`.`specification` (`name`) VALUES ('Diseño');
INSERT INTO `phoneadvice`.`specification` (`name`) VALUES ('Rendimiento');


INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('4', 'Es pequeño, es potente, el nuevo Xiaomi Redmi Go es la primera apuesta del fabricante Chino con Android Go, pensado para equipos economicos pero sin sacrificar potencia.', 'xiaomi/redmi_go', 'Redmi GO', '3', '1',1);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('3', 'Una renovación hermosa para una familia de equipos fantastica.', 'xiaomi/mi_mix_3', 'Mi Mix 3', '3', '3',2);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('6', 'Xiaomi se adelanta a todo el mundo y antes del lanzamiento del Samsung S10, presenta su nuevo buque de Guerra.', 'xiaomi/mi_9', 'Mi 9', '3', '3',3);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('3', 'Económico y potente', 'xiaomi/redmi_6', 'Redmi 6', '3', '1',4);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('2', 'Xiaomi sorprende con este celular de gama media con una cámara de 48 megapixeles', 'xiaomi/redmi_note_7', 'Redmi note 7', '3', '2',5);

INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('1', 'El ZenFone Max Pro es tu incansable compañero, siempre preparado para capturar los momentos especiales.', 'asus/zenfone_max_pro', 'Zenfone Max Pro', '6', '2',6);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('3', 'Diseñado para causar impresión, el ZenFone 5 está fabricado con materiales premium y técnicas de manufactura avanzadas. ', 'asus/zenfone_5', 'Zenfone 5', '6', '2',7);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('6', 'El ZenFone 5Z realiza cualquier tarea con fluidez y, gracias a su elegante diseño y compactas dimensiones, usarlo es un auténtico lujo.', 'asus/zenfone_5z', 'Zenfone 5z', '6', '3',8);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('7', 'El ZenFone 3 presume de un diseño ágil y exquisito inspirado en la belleza de la naturaleza. Es una obra de arte en metal y vidrio que captura el mundo con la máxima precisión. Un teléfono extraordinario para una vida menos ordinaria.', 'asus/zenfone_3', 'Zenfone 3', '6', '2',9);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`,`statistic_id`) VALUES ('1', 'Un celular económico, pero que no se quedará atrás al ejecutar tus aplicaciones', 'asus/zenfone_pegasus_4A', 'Zenfone Pegasus 4A', '6', '1',10);

INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('6', 'El resultado de 10 años siendo pioneros en dispositivos móviles, Galaxy S10. La nueva generación Galaxy ha llegado.', 'https://www.sunrise.ch/en/residential/geraete/handys/samsung-galaxy-s10.primaryproductimage.code-MDAwMDAwMDAwMDAwMDE5NjQw.format-hardware-configurator-l.png', 'Galaxy s10', '2', '3', 11);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('7', 'Uno de los mejores teléfonos del año que gracias al increíble lápiz S Pen, el Galaxy Note9 continúa teniendo un diseño único.', 'https://cdn.shopify.com/s/files/1/0181/5849/products/cellhelmet-tempered-glass-for-note-9.png?v=1533399816', 'Galaxy note 9', '2', '3', 12);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('5', 'La pantalla maximizada del Galaxy A70 te acerca aún más a lo que te importa: tus contenidos cobran vida en la pantalla Infinity-U FHD+ sAMOLED. Transmite vídeo o disfruta de tus series favoritas como nunca: la amplia relación de aspecto 20:9 brinda una experiencia sin igual y te transporta a un nuevo mundo de imagen', 'https://images.samsung.com/is/image/samsung/es-galaxy-a70-a705-sm-a705fzkuphe-frontblack-thumb-157773392?$PC_PRD_CARD_PNG$', 'Galaxy A70', '2', '2',13);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('3', 'Captura increíbles fotografías con el Galaxy A9, el primer Smartphone con cámara cuádruple. Sumérgete en su pantalla infinita de 6,3” y el envolvente sonido de Dolby Atmos. Su diseño elegante y ergonómico se sentirá perfecto en tus manos.', 'https://images.samsung.com/is/image/samsung/latin-galaxy-a9-a920-sm-a920fzkjtpa-frontblack-thumb-123814964', 'Galaxy A9', '2', '2', 14);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('4', 'Lleva tu experiencia visual a otro nivel. El Galaxy J4 tiene una gran pantalla HD de 5.5" que beneficia la relación de contraste y la calidad de las imágenes. Ahora puedes disfrutar de tus contenidos multimedia favoritos con colores más vivos y naturales.', 'https://www.pngfind.com/pngs/m/40-407372_samsung-galaxy-j4-details-hd-png-download.png', 'Galaxy J4', '2', '1', 15);

INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('2', 'El arte es un proceso de refinamiento, de eliminación de todo lo que no se necesita hasta que te queda algo puro, y a la vez poderoso.Eso es Nokia 9 PureView.', 'https://www.powerplanetonline.com/cdnassets/nokia_9_pureview_6gb128gb_ds_azul_01_l.jpg', '9 PureView', '8', '3', 16);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('5', 'Exprésate y cuenta tu historia, ya sea que te encuentres al aire libre, con sol pleno, o en una habitación tenuemente iluminada, el Nokia 7.1 y su pantalla se adaptarán dinámicamente al entorno para una espectacular experiencia dentro o afuera.', 'https://images.ctfassets.net/0weg701w29lb/2BQ3NWpPpi6A6GewAe6sOA/8bf530d131a65062356729838fd57ed7/nokia_7_1-user_guide-hero.png?fm=png', 'Nokia 7.1', '8', '2', 17);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('2', 'Un teléfono con el que puedes contar.Comienza con un exigente proceso de esculpido que transforma un solo bloque de aluminio sólido en el monobloque de un smartphone duradero que puedes llevar a cualquier parte.', 'https://catalogo.movistar.cl/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/n/o/nokia-nokia-61-black-front.png', 'Nokia 6.1', '8', '2', 18);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('4', 'Tu compañero de primera.Nokia 3.1 se ve y se siente superior. Llama la atención con sus sutiles curvas y sorprendentes lados de aluminio de corte de diamante. El nuevo Nokia 3 se siente cómodo en la mano gracias a una parte trasera curvada y una pantalla esculpida Corning® Gorilla® Glass.', 'hhttps://images.ctfassets.net/0weg701w29lb/773O8uhDA4qGsgYCA2KoKY/48ad9bb67ce6a0cebba33edd863e43db/nokia_3_1-user_guide-hero.png?fm=png', 'Nokia 3.1', '8', '1', 19);
INSERT INTO `phoneadvice`.`phone` (`assessment`, `description`, `image`, `model`, `brand_id`, `gamma_id`, 'statistic_id') VALUES ('1', 'Entretenimiento de larga duración. Accionado por una batería2 4000 mAh2, Nokia 2.1 se mantiene trabajando por dos días seguidos, así que puedes pasar menos tiempo en preocuparte por cargarlo y más tiempo haciendo lo que amas.', 'https://hnsfpau.imgix.net/5/images/detailed/86/HMD_Dynamo2_DarkBlueCopper_Front_LoRes_ROW_20180503.png?fit=fill&bg=0FFF&w=1500&h=844&auto=format,compress', 'Nokia 2.1', '8', '1', 20);

INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (1,1,6,11);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (1,2,3,12);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (1,3,7,13);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (1,4,3,14);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (1,5,4,15);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (1,6,5,16);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (2,1,3,17);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (2,2,4,18);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (2,3,3,19);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (2,4,1,20);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (2,5,5,21);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (2,6,6,22);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (3,1,7,23);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (3,2,4,24);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (3,3,7,25);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (3,4,6,26);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (3,5,1,27);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (3,6,7,28);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (4,1,3,29);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (4,2,5,30);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (4,3,2,31);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (4,4,1,32);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (4,5,6,33);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (4,6,3,34);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (5,1,4,35);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (5,2,4,36);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (5,3,6,37);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (5,4,2,38);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (5,5,4,39);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (5,6,4,40);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (6,1,1,41);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (6,2,1,42);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (6,3,6,43);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (6,4,2,44);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (6,5,4,45);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (6,6,2,46);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (7,1,2,47);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (7,2,1,48);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (7,3,6,49);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (7,4,2,50);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (7,5,4,51);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (7,6,5,52);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (8,1,3,53);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (8,2,7,54);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (8,3,4,55);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (8,4,2,56);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (8,5,1,57);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (8,6,7,58);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (9,1,2,59);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (9,2,3,60);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (9,3,1,61);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (9,4,3,62);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (9,5,2,63);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (9,6,6,64);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (10,1,1,65);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (10,2,1,66);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (10,3,2,67);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (10,4,4,68);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (10,5,6,69);
INSERT INTO `phoneadvice`.`phone_specification` (`phone_id`, `specification_id`, `assessment`, `statistic_id`) VALUES (10,6,1,70);

